export const SEARCH_USERS = {
    FETCH_REQUEST: 'SEARCH_USERS_FETCH_REQUEST',
    FETCH_SUCCESS: 'SEARCH_USERS_FETCH_SUCCESS',
    FETCH_ERROR: 'SEARCH_USERS_FETCH_ERROR'
};

export const SEARCH_PHOTOS = {
    FETCH_REQUEST: 'SEARCH_PHOTOS_FETCH_REQUEST',
    FETCH_SUCCESS: 'SEARCH_PHOTOS_FETCH_SUCCESS',
    FETC_ERROR: 'SEARCH_PHOTOS_FETCH_ERROR'
}