export const SET_USERS = 'SET_USERS';
export const APPEND_USERS = 'APPEND_USERS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const SEARCH_PHOTOS = {
    FETCH_REQUEST: 'SEARCH_PHOTOS_FETCH_REQUEST',
    FETCH_SUCCESS: 'SEARCH_PHOTOS_FETCH_SUCCESS',
    FETC_ERROR: 'SEARCH_PHOTOS_FETCH_ERROR'
}